[package]
name = "quill-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
stack-map = "1.0.5"
ebr = { version = "0.2.13" }
bztree = "0.2.0"
crossbeam-epoch = "0.9.18"
parking_lot = { version = "0.12.1", features = ["deadlock_detection"] }
parking_lot_core = { version = "0.9.0", features = ["deadlock_detection"] }
serial_test = "3.2.0"
dashmap = "6.1.0"
derive-with = "0.6.0"
derive-new = "0.7.0"
comfy-table = "7.1.0"
bincode = "1.3.3"
rand = "0.9.1"
fastrand = "2.0"
thiserror = "2.0.12"
nom = "7.0.0"
logos = "0.15.0"
strum = { version = "0.26", features = ["derive"]}
sqlparser = "0.34.0"
clap = { version = "4.3.19", features = ["derive", "cargo"] }
sqllogictest = "0.13.0"
regex = "1.9.1"
glob = "0.3.1"
rayon = "1.8.0"
string-error = "0.1.0"
memmap2 = "0.9.1"
natord = "1.0.0"
env_logger = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
fs4 = "0.8.4"
tempfile = "3.12.0"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }
tokio-stream = "0.1.16"
futures = "0.3.31"
bytes = "1.0.0"
rustyline = "15.0.0"
axum = { version = "0.7", features = ["macros", "json"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
serde_json = "1.0"
io-uring = { version = "0.6", optional = true }
crc32fast = "1.4"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.6" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand_chacha = "0.9"

[[bench]]
name = "storage_bench"
harness = false
