[package]
name = "sqldb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
parking_lot = "0.12.1"
dashmap = "6.1.0"
derive-with = "0.6.0"
derive-new = "0.7.0"
comfy-table = "7.1.0"
bincode = "1.3.3"
glob = "0.3.1"
rayon = "1.8.0"
string-error = "0.1.0"
memmap2 = "0.9.1"
natord = "1.0.0"
env_logger = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
fs4 = "0.8.4"
tempfile = "3.12.0"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["full"] }
tokio-stream = "0.1.16"
futures = "0.3.31"
bytes = "1.0.0"
rustyline = "15.0.0"
