app = "quillsql"         # 自定义
primary_region = "sin"           # 选最近区域

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  RUST_LOG = "info"
  # QUILL_DB_FILE = "/data/quill.db"  

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[[mounts]]
  source = "data"
  destination = "/data"